export const CREATE_BLOCKS_BOARD = 'CREATE_BLOCKS_BOARD';
export const RESET_BLOCKS_BOARD = 'RESET_BLOCKS_BOARD';
export const CHECK_POSSIBILITY = ' CHECK_POSSIBILITY';
export const DELETE_CLICKED_BLOCKS = 'DELETE_CLICKED_BLOCKS';
