export const CREATE_BLOCKS_BOARD = 'CREATE_BLOCKS_BOARD';
export const RESET_BLOCKS_BOARD = 'RESET_BLOCKS_BOARD';
export const CHECK_POSSIBILITY = ' CHECK_POSSIBILITY';
export const DELETE_CLICKED_BLOCKS = 'DELETE_CLICKED_BLOCKS';
export const UPDATE_COLOR_CLICKED_BLOCKS = 'UPDATE_COLOR_CLICKED_BLOCKS';
export const INCREASE_SCORE_POINTS = 'INCREASE_SCORE_POINTS';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const POINT_TRIGGER = 'POINT_TRIGGER';
